xxl:
  job:
    admin:
      addresses: http://127.0.0.1:9292/xxl-job-admin
    executor:
      appname: xhs-vote-xxl-job
      ip:
      port: 26008
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: -1
    accessToken:
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.22.26.222:3306/vote?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456